youtube/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('youtubeapp.urls'))
]

youtubeapp/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name = 'ytproject'


urlpatterns = [
    path('', views.index, name='home'),
    path('download/', views.download, name='download'),
    path('download/<resolution>/', views.yt_download_done, name="download_done")
]

youtubeapp/models.py
from django.db import models

# Create your models here.

youtubeapp/views.py
from django.shortcuts import render
from pytube import YouTube
import os


def index(request):
    return render(request, 'index.html')


def download(request):
    global url
    url = request.GET.get('url')
    yt = YouTube(url)
    video = []
    video = yt.streams.filter(progressive=True).all()
    embed_link = url.replace("watch?v=", "embed/")
    title = yt.title
    context = {'video': video, 'embed': embed_link, 'title': title}

    return render(request, 'download.html', context)


def yt_download_done(request, resolution):
    global url
    homedir = os.path.expanduser("~")
    dirs = homedir + '/Загрузки'
    if request.method == "POST":
        YouTube(url).streams.get_by_resolution(resolution).download(dirs)
        return render(request, 'done.html')
    else:
        return render(request, 'error.html')

youtubeapp/templates/done.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Download Done</title>
</head>
<body>
  <center><h1>Download Done</h1></center>
</body>
</html>

youtubeapp/templates/download.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title> Youtube Video</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  </head>
  <body>
<!--    Navbar start-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#"> Youtube Downloader </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav m1-auto">
        <li class="nav-item ">
          <a class="nav-link " aria-current="page" href="#"> Youtube Video Downloader</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Whatsapp Video Downloader</a>
        </li>


      </ul>
    </div>
  </div>
</nav>
<!--Navbar end-->



<!--main body start-->
<CENTER>
<div class="container">
  <h1> Your video: {{title}}</h1>
<div class=" mt-5 embed-responsive embed-responsive-16by9">
<iframe class="embed-responsive-item" src={{embed}}
        allowfullscreen></iframe>


  <div class="container">
<table class="table">
  <thead class="thread-dark">
    <tr class="table-dark">
      <th scope="col">Size</th>
      <th scope="col">Quality</th>
      <th scope="col">Type</th>
      <th scope="col">Download</th>
    </tr>
  </thead>
  {% for i in video %}
  <tbody>
    <tr>
      <th>{{i.filesize}}</th>
      <td>{{i.resolution}}</td>
      <td>{{i.type}}</td>
      <td>
        <form action="{% url 'ytproject:download_done' i.resolution %}" method="post">
          {% csrf_token %}
          <input type="submit" class="btn btn-success" value="Download">
        </form>
      </td>
    </tr>

    </tr>
  </tbody>
  {% endfor %}
</table>
  </div></div></div></CENTER>
<!--main body end-->


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>
  </body>
</html>

youtubeapp/templates/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>SomeThing Wrong</title>
</head>
<body>
  <center><h1>ERROR TRY AGAIN</h1></center>
</body>
</html>

youtubeapp/templates/index.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title> Youtube Downloader</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  </head>
  <body>
<!--    Navbar start-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#"> Youtube Downloader </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav m1-auto">
        <li class="nav-item ">
          <a class="nav-link " aria-current="page" href="#"> Youtube Video Downloader</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Whatsapp Video Downloader</a>
        </li>


      </ul>
    </div>
  </div>
</nav>
<!--Navbar end-->



<!--main body start-->
<div class="mt-5"><center><h1> Enter YouTube URL </h1></center></div>
<div class="container mt-5">
<div> <center>
    <form action="download/" method="GET">
  <div class="mb-3">

        <input name="url" type="text" class="form-control" placeholder="Enter Your Selected Youtube Video Link">
     <div id="emailHelp" class="form-text"> </div>
    </div>
    <center><button type="submit" class="btn btn-primary">Submit</button></center>
    </form>
<center>
</center>
</div>
<!--main body end-->


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </body>
</html>